### PR TITLE
Biggish refactor of project

### PR DESCRIPTION
**Pull request by gforsyth**
Ok guys, there's a lot of stuff here.  I'll try to be meticulous about documenting it here.

## General Structure
In line with the Python packaging guidelines, I've rearranged a bunch of stuff.  The basic layout should be as follows (per http://docs.python-guide.org/en/latest/writing/structure/#sample-repository):

```
pygbe/
pygbe/tree
pygbe/util
pygbe/geometry  #to be moved out of repo
pygbe/input_files #to be moved out of repo
examples/          #to be created
tests/                 #to be created
setup.py
README.md
```

The `bem_pycuda` folder has been renamed to `pygbe` (again following standard packaging guidelines) and the `util` folder has been moved into this renamed folder.  

I haven't moved the examples out of the repo yet and the tests are still there, too.  But this was becoming too many changes to put in one PR, so those can go on the TODO list.

## Imports

I've placed `__init__.py` files in all of the directories within PyGBe, thereby making them modules. 
Before, we were path-hacking using `sys.path` and then importing existing code as scripts.  
e.g. (from `matrixfree.py`)

```Python
sys.path.append('tree')
from FMMutils import *
sys.path.append('../util')
from semi_analytical import GQ_1D
```

This now works as follows:
```Python
from tree.FMMutils import *     #still need to fix the import *
from util.semi_analytical import GQ_1D
```

## `setup.py`

This was made quite difficult by SWIG, but I think I have it all figured out.  
First, the makefiles are gone.  All of them.  
Here's the new install procedure:

1. Clone the repo
2. `python setup.py install`

Done!  The `setup.py` file will automatically compile the SWIG'd files, link them against the numpy headers and then put them where they belong.  `setup.py` also handles the extra compilation flags Chris uses for performance, e.g. `-O3`, `-msse3`, etc...

To make sure that I didn't screw anything up re: timing (the regression tests are all fine), I ran both this version and the old version and we actually gain .2 seconds for the example in the README!  No idea why and not a big speedup at all, but most importantly, not a *slow-down!*

The one bit of nastiness in the `setup.py` file is that `setuptools` by default, runs the routine that would compile these SWIG files into python modules _after_ it has searched for all the `.py` files it wants to include in the package.  There are two solutions to this:

1. Run `setup.py` twice.  Easy, but weak.  
2. Subclass the installation and build routines to make it run `build_ext` first   (oh yeah)

This also creates a `pygbe` run script which is put into the $PATH of the current Python installation, so you can run `pygbe` from anywhere.

## New running procedures
This is the least completed part and is still naive, but the structure is there to make it quite good.

First, create an environment variable called `$PYGBE_DATA_DIR`.  This points to where the geometry files live, which, for now, looks like

```Bash
export PYGBE_DATA_DIR=/home/gil/git/pygbe/pygbe/
```

Then, to run the example we currently have in the README, you would do

```Bash
pygbe ~/git/pygbe/pygbe/input_files/lys.param ~/git/pygbe/pygbe/input_files/lys.config
```

or generally

```Bash
pygbe /full/path/to/param /full/path/to/config
```

This can and should be reworked to also use an ENV_VAR, either the same one as the geometry files or a separate one.   This is very much open to discussion.  

## One little extra
One of the possibly useful side-effects of installing PyGBe as a proper library is that you can run it in IPython and also debug from there.  So if you have `$PYGBE_DATA_DIR` set in your shell, fire up `ipython` and then you can do

```Python
from pygbe.main import main
main(argv=['','/path/to/lys.param','/path/to/lys.config'])
```
and it works!  (Note you do need to include the empty string as the first element of that `argv` list so that the indices match those produced by `sys.argv`

## Exeunt

@cdcooper84 , @ncclementi -- please take a look at this and try it out and let me know if there are bugs.  

## TODO:
* [x] update the README to reflect the new installation procedure
* [x] add a changelog so we can keep track of additions
* [x] use YAPF to get everything up to PEP8 standards
* [ ] maybe give PyGBe a version number?  And then figure out what kind of milestones we care about that would up that version number
* [ ] Write docs on how to use the regression tests
* [ ] set up a prompt to alert use to existing cache and remove if necessary
* [ ] Allow users to specify a filename for the cache
* [ ] Add contributor guide

### CODE REVIEW

**Comment by labarba** [comment]
Very impressed, @gforsyth — your kung-fu is good!

**Comment by cdcooper84** [comment]
Gil, this is AWESOME! The `setup.py` is very, very neat.

To make it even cleaner, the scripts `run_regression_tests.py`, `run_matrix_tests.py`, and `plot_Cext_freq.py` could go to the `scripts` folder. They are just scripts that call pygbe for different things, and not really a part of the code. For this same reason, perhaps they shouldn't even be part of the repo (the whole `scripts` folder, I mean), and could be kept somewhere else, but I'm open for discussion on this point.

You say you ran `run_regression_tests.py`, and they were all fine? That is enough for me to think that no bug has been introduced. I wanted to run them myself but at the moment I'm having some issues to run pygbe, but I should have that fixed soon.

About the $PYGBE_DATA_DIR variable, does this mean we should change the input files and put $PYGBE_DATA_DIR in there?

**Comment by cdcooper84** [comment]
I got PyGBe to run, but I'm having a few issues. Originally, the code dumped all the swig-generated files on the same directory, and I see you've moved that to the `build` directory, which I think is an excellent idea. The problem is that now it can't find one of them (specifically, it can't import _multipole). How can I tell it to look inside `build`?

**Comment by gforsyth** [comment]
@cdcooper84 -- it's actually a feature of `setuptools` that puts all the things listed under `ext_modules` into the `build` directory.  
But then everything that's in `pygbe` is installed to `/python_version/lib/site-packages/python2.7/PyGBe` so it's available to the system.  If everything is installed, you should be able to access the `multipole` module by doing

```Python
from pygbe.tree import multipole
```

**Comment by cdcooper84** [comment]
@gforsyth my bad, sorry! I hadn't realized the `setup.py` was throwing an error. I had pycuda installed locally, so `setup.py` couldn't find it and was unsuccessfully trying to install it.

Now it works, and it's awesome (I'll need to update many scripts, though).

**Comment by gforsyth** [comment]
@cdcooper84 regarding the `scripts` folder -- I think it can stay, although we can discuss further.  The regression tests and all other tests should definitely stay, but I'll move them to a folder `tests/` at the root of the repo.  In the future, we can even use `setup.py` to run the tests after install or after a change to ensure everything is still working.

**Comment by cdcooper84** [comment]
@gforsyth cool! let me know when you have moved everything and I'll update the scripts for regression testing with the new running procedures (along with the other scripts). We haven't done a test in a while and perhaps it's a good opportunity to do it before merging, for sanity check.

**Comment by gforsyth** [comment]
@cdcooper84 very good call.  everything is moved now so sanity checks may commence!

**Pull request merged**
