### PR TITLE
Class updates

### PR DESCRIPTION
**Pull request by gforsyth**
This is a partially finished refactor, making a bunch of independent functions class methods instead.  So the surface class now has a bunch of methods.  I've also removed the initialization of all of the surface attributes as empty lists, since they are created anyway.

More to do on this, but if anyone wanted to put eyes on it to see where it's going (and offer suggestions/concerns) it's here.

Oh, this also includes the python3 port stuff, too.  Most of the meat is in `surface.py` and `classes.py`

### CODE REVIEW

**Comment by cdcooper84** [comment]
Looks good to me! Just two questions:
1. The reason behind separating `surfaces.py` and `classes.py` is to avoid having a huge `classes.py` file?
2. You mention that this PR includes the Py3 stuff. Then PR #23 can be ignored?

**Comment by gforsyth** [comment]
Hey @cdcooper84 -- sorry I missed this.  I disabled notifications during my quals week and forgot to turn all of them back on.  

In re: 1. yes.  I was also going to break out the Field class into a separate file with all of its methods included there.  

2. Probably?  I think everything there is in here, although that should be ready to merge now, while this still needs a little extra work

**Comment by cdcooper84** [comment]
Thanks @gforsyth! Hope quals went well!
Yes, I actually see one Field method in `surface.py` (`initialize_field`). I think the `field` class with its method is small enough to fit in `classes.py`. How do you feel about that?
Do you prefer to have this PR merged and work on these details (if we think it's necessary) in a new PR?

**Comment by gforsyth** [comment]
> I think the field class with its method is small enough to fit in classes.py. How do you feel about that?

That's fine with me.  Once the class objects are more self contained it should be relatively trivial to move them around if we decide on a different organization scheme.  

> Do you prefer to have this PR merged and work on these details (if we think it's necessary) in a new PR?

My preference (barring objections from others) is to merge the Py3 PR first and keep this open to address the remaining changes.

**Comment by cdcooper84** [comment]
I'll take a look into the py3_port PR now. Let's keep this one open then.

**Comment by gforsyth** [comment]
Ok, i think this is ready for another look.  I ended up putting all the Field and Surface stuff back in classes

**Comment by cdcooper84** [comment]
I'm good with the new distribution of things, it looks nice and clean to me. Only one question (which is a small detail, really): should we rename `surface.py` to something like `class_initialization.py`? Or place the class initialization (`initialize_field` and `initialize_surface`) inside `classes.py`? Let me know what you think.

**Comment by gforsyth** [comment]
> should we rename surface.py to something like class_initialization.py?

That's a good call.  Let's leave it in its own file right now and rename, but we can stick it somewhere else later if we want to

**Comment by cdcooper84** [comment]
Cool! I'll do the change and merge

**Comment by ncclementi** [comment]
@cdcooper84 Hey Chris I'm running the regression tests and I will run the convergence ones too, to be sure everything is ok! Don't merge yet, I let you know if the test pass and then you merge or I can merge, is the same.

**Comment by cdcooper84** [comment]
Excellent, do the merge when tests pass. Thanks!

**Comment by gforsyth** [comment]
Ok, this took forever to iron out all the problems, but here are the convergence test results:
```console
------------------------------------------------------------
-------------------Running lysozyme test--------------------
------------------------------------------------------------
2016-10-04 18:52:20.664644

Passed Esolv test!

Passed iterations test! They are all within 3 iterations of reference
Summary:
Single: Esolv:  [-573.88458652 -516.68554792 -499.2789688  -493.66375908] , iterations:  [ 33.  34.  35.  39.]
Full  : Esolv:  [-581.46086759 -524.82092349 -507.6943087  -502.16682004] , iterations:  [ 36.  38.  41.  45.]
k=0   : Esolv:  [-578.11793321 -521.50134704 -504.4585046  -498.97822742] , iterations:  [ 33.  34.  36.  39.]
------------------------------------------------------------
----------------Running: molecule dirichlet-----------------
------------------------------------------------------------
2016-10-04 19:19:41.954270
Passed convergence test!

Number of elements : [  1024.   4096.  16384.  65536.]
Number of iteration: [ 27.  35.  46.  59.]
Interaction energy : [ 148380.06593201  154295.16915937  155825.92268576  156213.87770902]
Analytical solution: 156343.14478612485 kcal/mol
Error              : [ 0.05093334  0.01309924  0.00330825  0.00082682]
Total time         : [   10.03968596    40.33225918   243.17944026  1346.94874215]
------------------------------------------------------------
-----------------Running: molecule neumann------------------
------------------------------------------------------------
2016-10-04 19:37:36.790022
Passed convergence test!

Number of elements : [  1024.   4096.  16384.  65536.]
Number of iteration: [ 23.  32.  41.  53.]
Interaction energy : [ 1079151.90887056  1125132.83672754  1136980.16770378  1139974.05911672]
Analytical solution: 1140969.94323512 kcal/mol
Error              : [ 0.05418025  0.01388039  0.00349683  0.00087284]
Total time         : [    8.90078306    36.59543157   211.80986047  1153.88607335]
------------------------------------------------------------
-----------------Running: sphere_dirichlet------------------
------------------------------------------------------------
2016-10-04 19:37:37.328861
Passed convergence test!

Number of elements : [   512.   2048.   8192.  32768.]
Number of iteration: [ 12.  19.  27.  37.]
Total energy : [-12433232.98460513 -12546191.88831775 -12575192.75761317
 -12582520.59610148]
Analytical solution: -12584974.752619576 kcal/mol
Error              : [ 0.01205738  0.00308168  0.00077728  0.00019501]
Total time         : [   0.9798007     4.11615109   26.77735519  160.41277623]
------------------------------------------------------------
--------------Running: sphere molecule single---------------
------------------------------------------------------------
2016-10-04 19:45:22.579195
Passed convergence test!

Number of elements : [   512.   2048.   8192.  32768.]
Number of iteration: [ 23.  29.  39.  50.]
Total energy : [-9.64334849 -9.55084026 -9.52808787 -9.52243442]
Analytical solution: -9.520555194345807 kcal/mol
Error              : [ 0.0128977   0.00318102  0.0007912   0.00019739]
Total time         : [   2.74469566   10.4570384    69.19721174  381.9709518 ]
------------------------------------------------------------
---------------Running: sphere molecule stern---------------
------------------------------------------------------------
2016-10-04 20:08:55.297607
Passed convergence test!

Number of elements : [  1024.   4096.  16384.  65536.]
Number of iteration: [ 27.  35.  45.  59.]
Total energy : [-13.43943006 -13.27953315 -13.24033188 -13.23059366]
Analytical solution: -13.227355062790364 kcal/mol
Error              : [ 0.01603306  0.00394471  0.00098106  0.00024484]
Total time         : [    7.6994977     33.19058824   204.06263089  1166.87160587]
------------------------------------------------------------
------------------Running: sphere neumann-------------------
------------------------------------------------------------
2016-10-04 20:08:55.843409
Passed convergence test!

Number of elements : [   512.   2048.   8192.  32768.]
Number of iteration: [ 5.  5.  5.  4.]
Total energy : [ 88324544.12137185  89201471.03609908  89420462.4224074   89475025.02754802]
Analytical solution: 89493153.79640588 kcal/mol
Error              : [ 0.01305809  0.00325927  0.00081226  0.00020257]
Total time         : [  0.66537595   1.87820172   8.31117463  32.37350345]
------------------------------------------------------------
----------------Running: twosphere dirichlet----------------
------------------------------------------------------------
2016-10-04 20:22:18.318757
Passed convergence test!

Number of elements : [  1024.   4096.  16384.  65536.]
Number of iteration: [ 23.  33.  42.  56.]
Interaction energy : [ 2769828.94367073  2818625.35225317  2831194.84822163  2834373.38709177]
Analytical solution: 2835438.391685043 kcal/mol
Error              : [ 0.02313908  0.00592961  0.00149661  0.0003756 ]
Total time         : [   5.93267155   24.59628296  144.00872684  819.55750895]
------------------------------------------------------------
-----------------Running: twosphere neumann-----------------
------------------------------------------------------------
2016-10-04 20:24:47.724512
Passed convergence test!

Number of elements : [  1024.   4096.  16384.  65536.]
Number of iteration: [ 7.  7.  6.  6.]
Interaction energy : [ 24506695.59319952  25043072.01246279  25179742.39155185
  25214075.08515775]
Analytical solution: 25225537.22477205 kcal/mol
Error              : [ 0.02849658  0.00723335  0.00181542  0.00045439]
Total time         : [   2.95687175    8.49242139   34.7136116   145.67650533]
------------------------------------------------------------
-------------------Running: two molecules-------------------
------------------------------------------------------------
2016-10-04 20:45:47.981405
Passed convergence test!

Number of elements : [  1024.   4096.  16384.  65536.]
Number of iteration: [ 23.  31.  41.  54.]
Interaction energy : [ 0.11239648  0.11288481  0.11301124  0.11304374]
Analytical solution: 0.11305417212445824 kcal/mol
Error              : [  5.81752897e-03   1.49804693e-03   3.79708460e-04   9.22460966e-05]
Total time         : [    9.22529316    38.54945946   237.05943155  1311.77631783]
```

**Comment by cdcooper84** [comment]
Thanks @gforsyth! This looks ready to be merged, right?

**Comment by gforsyth** [comment]
Should be good to merge now that the conflicts are resolved!

**Comment by cdcooper84** [comment]
Cool! Just changed to 'all checks passed'. I'll go ahead and merge.

**Comment by gforsyth** [comment]
:tada:

**Pull request merged**
